ALTER TABLE work ALTER COLUMN pull_request SET DEFAULT 0;
ALTER TABLE work ALTER COLUMN merge_commit SET DEFAULT '';
ALTER TABLE work ALTER COLUMN merged_time SET NOT NULL;
ALTER TABLE work ALTER COLUMN deployed_time SET NOT NULL;
